language: elixir
elixir:
- 1.6.5
otp_release:
- '20.0'
install:
- mix local.rebar --force
- mix local.hex --force
- mix deps.get
jobs:
  include:
  - stage: style
    script: mix format --check-formatted
  - script: mix credo --strict
  - stage: build
    script: mix compile --warnings-as-errors
  - stage: test
    script: mix test
  - script: mix dialyzer --halt-exit-status
cache:
  directories:
  - _build
  - deps
notifications:
  slack:
    on_success: never
    on_failure: always
    secure: O3JYLm46szlQKOV827PtMXBJhk44dIcftooh+GpH4FyiDQIwwYWdHfNh6lrz9WAfDrPvH5uaGEQOux34HSpsRwpTpJYz76AIXN/sq+c5WL3Nqu3Lek2Srbd7Ww4X2s4YrLFFmXuCoc61fsiG6q9Y/HwXbz4d200dxQMffdp6EcocoqQZhGY55V5cPE6u/Z5Lq7vMdHYzDHLm3rJ9QuUxd/nI3IXdUZ8JOJA9wmlH95pkUmzrKaLEvo+WY9aajQ+CSCrHDwA/S0StaASgvAMBEehwAsrsSyY7EwsYP5hc9asvNbNbya0UGnYpk5J9MqAaGBLqjCGC4iijYdywfroL+zX4cDQyo5zbvlzqt+GYVUH1uSahHH/HFxw08GzwE8FC/Zo0zm4rnAxidTVgkkpbSsKAvNcEnMc8kjdfa+H3lj0TXmaalEYnbPG5xmrb3w3dPNwWzBOydzluJXKyjC1DX2aRLj+TyY4Pwag22XDW3qTGP/PUoKBUGNnyGdsokZwRsct7dXiaRuLXPXyw6jg+Xx+QjHCuRmDrTxmx3fXqejQ0w8PWQGlhRDUde1L3fb4uwzBT7UmXtC13yASPbZ7ta5buITagGYNqHVEoTfXQj8lU1HjRykRn1Wpl1qwjduEd7IVNHklslxBXq+qIb2V1LZsc4wvEGz7f5leGSYYkLxw=
